### ISSUE TITLE
Title lines are not based on screen size

### ISSUE THREAD

**Issue by mosheavni** [Ramilito/kubectl.nvim#111] opened 2024-07-18 07:00 UTC
**Describe the bug**

the -------- Pods ---------- divider is not calculating the size of the screen to determine the number of `-`

<img width="1698" alt="image" src="https://github.com/user-attachments/assets/c2a34ef8-1de7-4b10-abcb-8c1379a581d7">

**To Reproduce**

2. Press '....'

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. OSX]
 - Neovim version [e.g. 0.10]

**Additional context**

**Comment by mosheavni** [comment] 2024-07-18 07:26
from what I investigated a little, relativenumber and number are not taken into account, probably statuscolumn as well
https://github.com/mosheavni/kubectl.nvim/blob/d78e0ea5b8d0c01ad63552de9593738994d7c564/lua/kubectl/utils/tables.lua#L90-L91

**Comment by Ramilito** [comment] 2024-07-18 07:30
Yeah that's probably the cause, will look into it, managed to replicate it when setting the options:
```
vim.opt.wrap = true
vim.opt.linebreak = true
```


This is how mine looks like when I don't set those options:
![image](https://github.com/user-attachments/assets/7f96fe92-8e92-474e-8672-b630730fb969)

**Comment by Ramilito** [comment] 2024-07-18 08:04
substracted all the extra stuff and seems to work now!

FIxed in: 428ba43f8b91d933c644f3d9491a6db51dbd6615

**Closed by Ramilito** 2024-07-18 08:04 UTC
