### ISSUE TITLE
filter does not work when switching from pod to ingress view

### ISSUE THREAD

**Issue by mosheavni** [Ramilito/kubectl.nvim#308] opened 2024-09-10 14:07 UTC
**Describe the bug**
ok this is weird, I started experiencing it a while ago but disregarded it.
now it's bugging me
when opening straight to pods view, then applying a filter, then switching to ingress, even though there are resources that should match the filter, I see 0 ingresses!
I ran a `git bisect` and found that this: b637e870ba5942697314afa1aa65547a3ba35e95 is the first bad commit:

```
b637e870ba5942697314afa1aa65547a3ba35e95 is the first bad commit
```
which makes this the last good commit: a07612541e5b4fe05f5309460def2e1a0ced5f75
```
a07612541e5b4fe05f5309460def2e1a0ced5f75
```

**Bad commit reproduction**
1. make sure we're aligned to origin/maon
2. open `k8s` on `pods` view
3. filter for a value
4. switch to `ingress` view
5. filter is applied, ingress exists, yet I see 0!
![2024-09-10_16-56-18 (1)](https://github.com/user-attachments/assets/1628bfb1-4a81-45ee-9d80-96122ce6c13d)

**Good commit reproduction**
1. reset to this commit:
```
git checkout a07612541e5b4fe05f5309460def2e1a0ced5f75
```
2. open `k8s` on `pods` view
3. filter for a value
4. switch to `ingress` view
5. filter is applied, ingress exists, i see the ingress

![2024-09-10_17-06-04 (1)](https://github.com/user-attachments/assets/bda22bf4-bd91-427e-acca-a0930d85bbac)

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. OSX]
 - Neovim version [e.g. 0.10]

**Additional context**

**Comment by Ramilito** [comment] 2024-09-10 17:27
This is super weird, that commit isn't even touching the code relevant to the filter.
I'm not able to reproduce even though I see it happening in the gif!

![debug_ingress](https://github.com/user-attachments/assets/624abe2a-276b-424d-9027-20323a316bfc)

Could it be something with the state files? Could you check if it looks ok?

**Comment by mosheavni** [comment] 2024-09-12 11:42
> This is super weird, that commit isn't even touching the code relevant to the filter. I'm not able to reproduce even though I see it happening in the gif!
> 
> ![debug_ingress](https://private-user-images.githubusercontent.com/8473233/366146962-624abe2a-276b-424d-9027-20323a316bfc.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxNDE2MDksIm5iZiI6MTcyNjE0MTMwOSwicGF0aCI6Ii84NDczMjMzLzM2NjE0Njk2Mi02MjRhYmUyYS0yNzZiLTQyNGQtOTAyNy0yMDMyM2EzMTZiZmMuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTJUMTE0MTQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDhjYzUzY2IwNmY2NGY2OTc5YjZkMTE5ODc1NmYwY2JjMzVjMzU2NDRmYTZmZjUxMGNlOGFjMmUzNTkxZDFiYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.flqYw_sIkvPALKMDPyKAzG989t1AU4nJQHCydcWCYFw) [ ![debug_ingress](https://private-user-images.githubusercontent.com/8473233/366146962-624abe2a-276b-424d-9027-20323a316bfc.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxNDE2MDksIm5iZiI6MTcyNjE0MTMwOSwicGF0aCI6Ii84NDczMjMzLzM2NjE0Njk2Mi02MjRhYmUyYS0yNzZiLTQyNGQtOTAyNy0yMDMyM2EzMTZiZmMuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTJUMTE0MTQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDhjYzUzY2IwNmY2NGY2OTc5YjZkMTE5ODc1NmYwY2JjMzVjMzU2NDRmYTZmZjUxMGNlOGFjMmUzNTkxZDFiYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.flqYw_sIkvPALKMDPyKAzG989t1AU4nJQHCydcWCYFw) ](https://private-user-images.githubusercontent.com/8473233/366146962-624abe2a-276b-424d-9027-20323a316bfc.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxNDE2MDksIm5iZiI6MTcyNjE0MTMwOSwicGF0aCI6Ii84NDczMjMzLzM2NjE0Njk2Mi02MjRhYmUyYS0yNzZiLTQyNGQtOTAyNy0yMDMyM2EzMTZiZmMuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTJUMTE0MTQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDhjYzUzY2IwNmY2NGY2OTc5YjZkMTE5ODc1NmYwY2JjMzVjMzU2NDRmYTZmZjUxMGNlOGFjMmUzNTkxZDFiYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.flqYw_sIkvPALKMDPyKAzG989t1AU4nJQHCydcWCYFw) [ ](https://private-user-images.githubusercontent.com/8473233/366146962-624abe2a-276b-424d-9027-20323a316bfc.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxNDE2MDksIm5iZiI6MTcyNjE0MTMwOSwicGF0aCI6Ii84NDczMjMzLzM2NjE0Njk2Mi02MjRhYmUyYS0yNzZiLTQyNGQtOTAyNy0yMDMyM2EzMTZiZmMuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTJUMTE0MTQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDhjYzUzY2IwNmY2NGY2OTc5YjZkMTE5ODc1NmYwY2JjMzVjMzU2NDRmYTZmZjUxMGNlOGFjMmUzNTkxZDFiYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.flqYw_sIkvPALKMDPyKAzG989t1AU4nJQHCydcWCYFw)
> 
> Could it be something with the state files? Could you check if it looks ok?

checked and state file looks fine. i doubled that and removed the state file completely, but the issue stills seem to happen

**Comment by mosheavni** [comment] 2024-09-18 13:47
this is bad. I have to close and reopen hundred times a day..

**Comment by Ramilito** [comment] 2024-09-18 14:00
oh man, that's not acceptable, so hard to debug something I can't recreate.
I'll try more tonight, the overview is ready to be checked in, not completed but it gives us something to build on at least. After that, I'll try to fix this.

**Comment by mosheavni** [comment] 2024-09-18 14:03
> Owner

i appreciate it.

**Comment by Ramilito** [comment] 2024-09-19 08:48
yeah something seems to be off there, just not sure why I can't replicate it.
Did a guess fix in d798b5a033d337074a0824c6958f255a09a4c640 and merged to main, but not sure if it solves it, could you test it out?

**Comment by mosheavni** [comment] 2024-09-19 10:30
doesn't seem to solve it.
I'm trying to debug it for the last hour, it seems that the problem lies within find.is_in_table

**Comment by mosheavni** [comment] 2024-09-19 10:47
for some reason this prevents the problem from happening:
https://github.com/Ramilito/kubectl.nvim/pull/319

**Comment by Ramilito** [comment] 2024-09-19 11:01
I love it, mystery programming 😅

**Closed** 2024-09-19 11:02 UTC
