### ISSUE TITLE
bug: "describe" on deployment replaces buffer with the yaml file and at the same time shows a float window with the yaml file

### ISSUE THREAD

**Issue by idelice** [Ramilito/kubectl.nvim#45] opened 2024-06-12 21:49 UTC
Steps
1. go to deployments
2. press "d"

What happens
It replaces the UI with the yaml file and at the same time, it creates a float window with the exact same float window

Excepted
*Only* float window pop ups with the yaml file and *not* replacing existing buffer.

**Comment by Ramilito** [comment] 2024-06-13 07:03
Is it something that happens every time or just sometimes?
I'm testing it out on main and the lazy boilerplate you shared but not getting that behaviour.
The reason that could happen is if it confuses currentbuffer with the previous one, can you tell me more about how you get that to happen?

**Comment by idelice** [comment] 2024-06-13 10:26
Everytime, but after merging latest stuff from main, the issue seems to be gone

**Comment by idelice** [comment] 2024-06-13 10:26
I suspect it was related to the filter stuff.. it happened every time after filtering deployments

**Comment by Ramilito** [comment] 2024-06-13 12:10
Closing for now but keeping an eye out, might be time to add some automated tests as well for regression testing

**Comment by idelice** [comment] 2024-06-13 14:57
Ok - seems like i can reproduce this every time doing the following:



1. open plugin
2. press "1" -> deployments
3. filter an existing deployment
4.press "d" on deployment



@Ramilito

**Comment by Ramilito** [comment] 2024-06-13 19:37
hmm I'm still not able to reproduce (tried with the lazy_boilerplate as well), can you try to pinpoint where the issue is? it should probably be either in the actions.buffer or actions.floating_buffer

**Comment by Ramilito** [comment] 2024-07-20 13:07
Could you check if this is still happening with latest (I found a small bug that could have been the cause) @idelice

**Comment by Ramilito** [comment] 2024-08-08 05:24
Can't reproduce, if it's still happening please reopen the issue!

**Closed** 2024-08-08 05:23 UTC

**Comment by idelice** [comment] 2024-08-08 08:16
Haven't had any issues for some time now. I'll re-open if issue persists
